// set-env.js for BrewBean - generates environment.ts from .env
const fs = require('fs');
const path = require('path');

const envDir = path.join(__dirname, '..', 'src', 'environments');

// Read .env file
const envFile = path.join(__dirname, '..', '.env');
let envContent = '';

try {
  envContent = fs.readFileSync(envFile, 'utf8');
} catch (err) {
  console.log('No .env file found, using defaults');
}

const envVars = {};
envContent.split('\n').forEach(line => {
  const match = line.match(/^([^=]+)=(.*)$/);
  if (match) {
    envVars[match[1]] = match[2];
  }
});

const envTs = `// Generated by set-env.js - DO NOT EDIT
export const environment = {
  production: false,
  neonAuthUrl: '${envVars.VITE_NEON_AUTH_URL || 'https://ep-brewbean-loyalty.neonauth.c-4.us-east-1.aws.neon.tech/neondb/auth'}',
  databaseUrl: '${envVars.VITE_DATABASE_URL || 'https://ep-brewbean-loyalty.c-4.us-east-1.aws.neon.tech/rest/v1'}',
  databaseSchema: '${envVars.VITE_DATABASE_SCHEMA || 'public'}',
  stripePublicKey: '${envVars.VITE_STRIPE_PUBLIC_KEY || ''}',
};
`;

const envProdTs = `// Generated by set-env.js - DO NOT EDIT
export const environment = {
  production: true,
  neonAuthUrl: '${envVars.VITE_NEON_AUTH_URL || 'https://ep-brewbean-loyalty.neonauth.c-4.us-east-1.aws.neon.tech/neondb/auth'}',
  databaseUrl: '${envVars.VITE_DATABASE_URL || 'https://ep-brewbean-loyalty.c-4.us-east-1.aws.neon.tech/rest/v1'}',
  databaseSchema: '${envVars.VITE_DATABASE_SCHEMA || 'public'}',
  stripePublicKey: '${envVars.VITE_STRIPE_PUBLIC_KEY || ''}',
};
`;

fs.mkdirSync(envDir, { recursive: true });
fs.writeFileSync(path.join(envDir, 'environment.ts'), envTs);
fs.writeFileSync(path.join(envDir, 'environment.prod.ts'), envProdTs);

console.log('✅ Environment files generated successfully');
